CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AuditEvents" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ActorUserId" uuid,
    "LicenseKeyId" uuid,
    "Action" character varying(48) NOT NULL,
    "Outcome" character varying(24) NOT NULL,
    "OccurredAt" timestamp with time zone NOT NULL,
    "Detail" character varying(256),
    CONSTRAINT "PK_AuditEvents" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "Username" character varying(32) NOT NULL,
    "NormalizedUsername" character varying(32) NOT NULL,
    "PasswordHash" character varying(255) NOT NULL,
    "IsAdmin" boolean NOT NULL,
    "IsBlocked" boolean NOT NULL,
    "FailedLogins" integer NOT NULL,
    "LockedUntil" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastLoginAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "LicenseKeys" (
    "Id" uuid NOT NULL,
    "Prefix" character varying(16) NOT NULL,
    "KeyHash" character varying(64) NOT NULL,
    "DurationDays" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ActivatedAt" timestamp with time zone,
    "ExpiresAt" timestamp with time zone,
    "RevokedAt" timestamp with time zone,
    "IsBlocked" boolean NOT NULL,
    "AssignedUserId" uuid,
    "DeviceHash" character varying(64),
    "LastLoginAt" timestamp with time zone,
    CONSTRAINT "PK_LicenseKeys" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LicenseKeys_Users_AssignedUserId" FOREIGN KEY ("AssignedUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Sessions" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "AccessHash" character varying(64) NOT NULL,
    "RefreshHash" character varying(64) NOT NULL,
    "DeviceHash" character varying(64) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "AccessExpiresAt" timestamp with time zone NOT NULL,
    "RefreshExpiresAt" timestamp with time zone NOT NULL,
    "RevokedAt" timestamp with time zone,
    CONSTRAINT "PK_Sessions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AuditEvents_LicenseKeyId" ON "AuditEvents" ("LicenseKeyId");

CREATE INDEX "IX_AuditEvents_OccurredAt" ON "AuditEvents" ("OccurredAt");

CREATE UNIQUE INDEX "IX_LicenseKeys_AssignedUserId" ON "LicenseKeys" ("AssignedUserId");

CREATE UNIQUE INDEX "IX_LicenseKeys_KeyHash" ON "LicenseKeys" ("KeyHash");

CREATE INDEX "IX_LicenseKeys_Prefix" ON "LicenseKeys" ("Prefix");

CREATE UNIQUE INDEX "IX_Sessions_AccessHash" ON "Sessions" ("AccessHash");

CREATE UNIQUE INDEX "IX_Sessions_RefreshHash" ON "Sessions" ("RefreshHash");

CREATE INDEX "IX_Sessions_UserId" ON "Sessions" ("UserId");

CREATE UNIQUE INDEX "IX_Users_NormalizedUsername" ON "Users" ("NormalizedUsername");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261005183449_InitialLicensing', '10.0.12');

COMMIT;

